name: angers
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  provider: ^4.3.0
  outline_material_icons: ^0.1.1
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.8
  animations: ^1.1.1
  url_launcher: ^5.5.0
  location: ^3.0.2
  google_maps_flutter: ^0.5.30
  uuid: ^2.2.0
  cached_network_image: ^2.2.0+1
  http: ^0.12.2
  latlong: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/